DATASET_ROOT: "../_data/wallpapers"
JSON_PATH: "train.json"
BATCH_SIZE: 2
IMAGE_SIZE: [540, 960]
WORKERS: 8
PIN_MEMORY: True
SHUFFLE: True

LEARNING_RATE: 0.0001
BETAS: [0.9, 0.999]
EPS: 0.00000001
WEIGHT_DECAY: 0.00001

MILESTONES: [10]
GAMMA: 0.5

NUM_EPOCHS: 20
TEST: False
OUT_PATH: "./runs"
LOAD_MODEL: False
SAVE_MODEL: False
CHECKPOINT_FILE: "normal.pth"